-- SUB-CATEGORIES SETUP

-- 1. Create Product Subcategories Table
CREATE TABLE public.product_subcategories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    category_id bigint REFERENCES public.product_categories(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE(name, category_id)
);

-- 2. Add subcategory_id to Products
ALTER TABLE public.products 
ADD COLUMN subcategory_id bigint REFERENCES public.product_subcategories(id) ON DELETE SET NULL;

-- 3. RLS Policies
ALTER TABLE public.product_subcategories ENABLE ROW LEVEL SECURITY;

-- Allow public read
CREATE POLICY "Public read for subcategories" ON public.product_subcategories FOR SELECT USING (true);

-- Admin Full Access (using the same is_admin function as categories)
CREATE POLICY "Admin full access for subcategories" ON public.product_subcategories FOR ALL TO authenticated USING (public.is_admin());

-- 4. Initial Seed Data (Optional - just to have some examples)
-- Assuming some IDs from categories. In a real scenario, we might need to query them.
-- But for the migration, we'll let the user add them via UI.
