-- PRODUCTS & CATEGORIES SETUP

-- 1. Create Product Categories Table
CREATE TABLE public.product_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text UNIQUE NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- 2. Create Products Table
CREATE TABLE public.products (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name text NOT NULL,
    description text,
    category_id bigint REFERENCES public.product_categories(id),
    price numeric NOT NULL,
    stock_quantity integer DEFAULT 0,
    image_url text,
    is_active boolean DEFAULT true,
    sales_count integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- 3. RLS Policies
ALTER TABLE public.product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Allow public read (for affiliates to see catalog)
CREATE POLICY "Public read for categories" ON public.product_categories FOR SELECT USING (true);
CREATE POLICY "Public read for products" ON public.products FOR SELECT USING (true);

-- Admin Full Access (assuming is_admin function exists from previous phase)
CREATE POLICY "Admin full access for categories" ON public.product_categories FOR ALL TO authenticated USING (public.is_admin());
CREATE POLICY "Admin full access for products" ON public.products FOR ALL TO authenticated USING (public.is_admin());

-- 4. Initial Seed Data
INSERT INTO public.product_categories (name) VALUES 
('Colchões'), 
('Acessórios'), 
('Conforto'), 
('Camas'), 
('Enxoval');
