-- V5 REGISTRATION TRIGGER - CLASSE A
-- Este script resolve a falha em que o usuário era criado em auth.users e user_profiles, mas faltava em affiliates.

-- 1. Tabela de Logs de Debug (Garantir que existe)
CREATE TABLE IF NOT EXISTS public.debug_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text,
    message text,
    metadata jsonb,
    created_at timestamp with time zone DEFAULT now()
);

-- 2. Função de Gatilho Robusta
CREATE OR REPLACE FUNCTION public.handle_new_affiliate_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
 AS $function$
 DECLARE
   v_full_name text;
   v_sponsor_id uuid;
   v_org_id uuid;
   v_sponsor_code text;
   v_error_msg text;
   v_login text;
 BEGIN
   -- A. Log de Início
   INSERT INTO public.debug_logs (operation, message, metadata) 
   VALUES ('signup_start', 'Iniciando processamento: ' || COALESCE(new.email, 'S/ Email'), new.raw_user_meta_data);

   -- B. Determinar Dados Básicos
   v_login := COALESCE(new.raw_user_meta_data ->> 'login', split_part(new.email, '@', 1));
   v_full_name := TRIM(CONCAT_WS(' ', new.raw_user_meta_data ->> 'nome', new.raw_user_meta_data ->> 'sobrenome'));
   IF v_full_name = '' THEN v_full_name := v_login; END IF;

   -- C. Determinar Organização (Fallback para Classe A)
   BEGIN
     v_org_id := (new.raw_user_meta_data ->> 'organization_id')::uuid;
   EXCEPTION WHEN OTHERS THEN
     v_org_id := NULL;
   END;

   IF v_org_id IS NULL THEN
      SELECT id INTO v_org_id FROM public.organizations WHERE name = 'Classe A' LIMIT 1;
   END IF;
   
   IF v_org_id IS NULL THEN
      -- Se a tabela de organizações estiver vazia ou Classe A não existir
      v_org_id := '5111af72-27a5-41fd-8ed9-8c51b78b4fdd'::uuid; -- ID Hardcoded da Classe A como último recurso
   END IF;

   -- D. Resolver Padrinho (Sponsor)
   v_sponsor_code := NULLIF(new.raw_user_meta_data ->> 'sponsor_code', '');
   IF v_sponsor_code IS NOT NULL THEN
     -- Buscamos pelo referral_code na mesma organização
     SELECT id INTO v_sponsor_id 
     FROM public.affiliates 
     WHERE LOWER(referral_code) = LOWER(v_sponsor_code)
     AND organization_id = v_org_id
     LIMIT 1;

     IF v_sponsor_id IS NULL THEN
        INSERT INTO public.debug_logs (operation, message) 
        VALUES ('signup_warning', 'Padrinho não encontrado: ' || v_sponsor_code);
     END IF;
   END IF;

   -- E. Criar Perfil do Usuário
   -- Nota: Incluímos todas as colunas que a tabela user_profiles agora possui
   BEGIN
     INSERT INTO public.user_profiles (
       id, email, role, full_name, login, 
       whatsapp, cpf, cnpj, registration_type, 
       organization_id, sponsor_id, referrer_id,
       status, rank, created_at, updated_at
     )
     VALUES (
       new.id, 
       new.email, 
       COALESCE(new.raw_user_meta_data ->> 'role', 'affiliate'),
       v_full_name,
       v_login,
       new.raw_user_meta_data ->> 'whatsapp',
       new.raw_user_meta_data ->> 'cpf',
       new.raw_user_meta_data ->> 'cnpj',
       new.raw_user_meta_data ->> 'registration_type',
       v_org_id,
       v_sponsor_id,
       v_sponsor_id, -- Mantemos paridade entre sponsor e referrer
       'active',
       'Consultor',
       new.created_at, 
       new.created_at
     );
   EXCEPTION WHEN OTHERS THEN
     GET STACKED DIAGNOSTICS v_error_msg = MESSAGE_TEXT;
     INSERT INTO public.debug_logs (operation, message, metadata) 
     VALUES ('user_profiles_error', v_error_msg, new.raw_user_meta_data);
     RAISE EXCEPTION 'Falha ao criar perfil: %', v_error_msg;
   END;

   -- F. Criar Registro de Afiliado
   BEGIN
     INSERT INTO public.affiliates (
       user_id, email, full_name, referral_code, 
       whatsapp, cpf, cnpj, organization_id, sponsor_id, 
       is_active, created_at, updated_at
     )
     VALUES (
       new.id,
       new.email,
       v_full_name,
       v_login,
       new.raw_user_meta_data ->> 'whatsapp',
       new.raw_user_meta_data ->> 'cpf',
       new.raw_user_meta_data ->> 'cnpj',
       v_org_id,
       v_sponsor_id,
       true,
       new.created_at,
       new.created_at
     );
   EXCEPTION WHEN OTHERS THEN
     GET STACKED DIAGNOSTICS v_error_msg = MESSAGE_TEXT;
     INSERT INTO public.debug_logs (operation, message, metadata) 
     VALUES ('affiliates_error', v_error_msg, new.raw_user_meta_data);
     RAISE EXCEPTION 'Falha ao criar afiliado: %', v_error_msg;
   END;

   -- G. Criar Configurações Iniciais
   BEGIN
     INSERT INTO public.user_settings (user_id, organization_id, created_at, updated_at)
     VALUES (new.id, v_org_id, new.created_at, new.created_at);
   EXCEPTION WHEN OTHERS THEN 
     NULL; -- Permitimos falha aqui para não travar o cadastro
   END;
   
   INSERT INTO public.debug_logs (operation, message) 
   VALUES ('signup_success', 'Cadastro concluído para: ' || new.email);

   RETURN new;
 END;
 $function$;

-- 3. Re-criar Gatilho
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_affiliate_user();
