-- SECURITY SCHEMA SETUP

-- 1. Create Security Logs Table
CREATE TABLE IF NOT EXISTS public.security_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email text,
    ip_address text,
    location text,
    device_info text,
    event_type text NOT NULL, -- 'login_success', 'login_failure', 'password_change', etc.
    status text NOT NULL, -- 'success', 'failure', 'warning'
    created_at timestamp with time zone DEFAULT now()
);

-- 2. RLS Policies
ALTER TABLE public.security_logs ENABLE ROW LEVEL SECURITY;

-- Admins can view all logs
CREATE POLICY "Admins can view security logs" 
ON public.security_logs 
FOR SELECT 
TO authenticated 
USING (public.is_admin());

-- System/App can insert logs (or via edge function/trigger)
-- For now, allow authenticated users to insert their own login events if needed, 
-- but usually this is done backend-side or via trigger.
CREATE POLICY "Everyone (auth) can insert security logs" 
ON public.security_logs 
FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- 3. Initial Seed Data (Optional)
INSERT INTO public.security_logs (user_email, ip_address, location, device_info, event_type, status)
VALUES 
('master_admin@classea.com', '189.45.122.10', 'São Paulo, BR', 'Windows / Chrome', 'login_success', 'success'),
('unknown', '45.12.88.231', 'Kiev, UA', 'Linux / Firefox', 'login_failure', 'failure');
