-- REPLICATION SCRIPT FOR CLASSE A DATABASE (CLEAN SLATE VERSION)
-- WARNING: This will DELETE all existing data in the tables below.
-- Copy and paste this into the Supabase SQL Editor (https://supabase.com/dashboard/project/clnuievcdnbwqbyqhwys/sql)

-- 0. CLEANUP (Forcefully remove everything to fix structure issues)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_affiliate_user() CASCADE;
DROP TABLE IF EXISTS public.withdrawals CASCADE;
DROP TABLE IF EXISTS public.company_purchases CASCADE;
DROP TABLE IF EXISTS public.customer_coupons CASCADE;
DROP TABLE IF EXISTS public.company_cashiers CASCADE;
DROP TABLE IF EXISTS public.companies CASCADE;
DROP TABLE IF EXISTS public.user_settings CASCADE;
DROP TABLE IF EXISTS public.affiliates CASCADE;
DROP TABLE IF EXISTS public.user_profiles CASCADE;

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. TABLES

-- user_profiles (Supabase version uses Auth UUID)
CREATE TABLE public.user_profiles (
    id uuid REFERENCES auth.users(id) PRIMARY KEY,
    mocha_user_id text UNIQUE,
    cpf text UNIQUE,
    role text DEFAULT 'affiliate'::text,
    is_active boolean DEFAULT true,
    sponsor_id uuid,
    company_name text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    email text
);

-- affiliates
CREATE TABLE public.affiliates (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id),
    full_name text,
    cpf text UNIQUE,
    email text UNIQUE,
    whatsapp text,
    referral_code text UNIQUE,
    sponsor_id uuid REFERENCES public.affiliates(id),
    is_active boolean DEFAULT true,
    is_verified boolean DEFAULT false,
    last_access_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    position_slot integer
);

-- companies
CREATE TABLE public.companies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social text NOT NULL,
    nome_fantasia text NOT NULL,
    cnpj text UNIQUE NOT NULL,
    email text UNIQUE NOT NULL,
    telefone text NOT NULL,
    responsavel text NOT NULL,
    senha_hash text NOT NULL,
    endereco text,
    site_instagram text,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- company_cashiers
CREATE TABLE public.company_cashiers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint REFERENCES public.companies(id),
    user_id uuid UNIQUE REFERENCES auth.users(id),
    name text,
    cpf text UNIQUE NOT NULL,
    password_hash text NOT NULL,
    is_active boolean DEFAULT true,
    last_access_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- customer_coupons
CREATE TABLE public.customer_coupons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_code text UNIQUE NOT NULL,
    user_id uuid REFERENCES auth.users(id),
    affiliate_id uuid REFERENCES public.affiliates(id),
    cpf text UNIQUE NOT NULL,
    last_used_at timestamp with time zone,
    total_usage_count integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- company_purchases
CREATE TABLE public.company_purchases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint REFERENCES public.companies(id),
    cashier_id bigint REFERENCES public.company_cashiers(id),
    customer_coupon_id bigint REFERENCES public.customer_coupons(id),
    customer_coupon text NOT NULL,
    cashier_cpf text,
    purchase_value numeric NOT NULL,
    cashback_percentage numeric NOT NULL,
    cashback_generated numeric NOT NULL,
    purchase_date date NOT NULL,
    purchase_time time with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- withdrawals
CREATE TABLE public.withdrawals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id),
    amount_requested numeric NOT NULL,
    fee_amount numeric DEFAULT 0.00,
    net_amount numeric NOT NULL,
    status text DEFAULT 'pending'::text,
    pix_key text NOT NULL,
    processed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

-- user_settings
CREATE TABLE public.user_settings (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid UNIQUE REFERENCES auth.users(id),
    pix_key text,
    leg_preference text DEFAULT 'automatic'::text,
    total_earnings numeric DEFAULT 0.00,
    available_balance numeric DEFAULT 0.00,
    frozen_balance numeric DEFAULT 0.00,
    is_active_this_month boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- 3. FUNCTIONS

CREATE OR REPLACE FUNCTION public.handle_new_affiliate_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  v_full_name text;
BEGIN
  -- Build full name safely
  v_full_name := TRIM(CONCAT_WS(' ', 
    new.raw_user_meta_data ->> 'nome', 
    new.raw_user_meta_data ->> 'sobrenome'
  ));
  
  IF v_full_name = '' THEN
    v_full_name := 'Novo Afiliado';
  END IF;

  -- 1. Create Profile
  INSERT INTO public.user_profiles (id, email, created_at, updated_at)
  VALUES (new.id, new.email, new.created_at, new.created_at);

  -- 2. Create Affiliate
  INSERT INTO public.affiliates (user_id, email, full_name, referral_code, created_at, updated_at)
  VALUES (
    new.id,
    new.email,
    v_full_name,
    new.raw_user_meta_data ->> 'login',
    new.created_at,
    new.updated_at
  );

  -- 3. Create Settings
  INSERT INTO public.user_settings (user_id, created_at, updated_at)
  VALUES (
    new.id,
    new.created_at,
    new.created_at
  );
  
  RETURN new;
END;
$function$;

-- 4. RLS POLICIES
ALTER TABLE public.affiliates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Affiliates can view their own data" ON public.affiliates;
CREATE POLICY "Affiliates can view their own data" ON public.affiliates FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Allow public email lookup by referral_code" ON public.affiliates;
CREATE POLICY "Allow public email lookup by referral_code" ON public.affiliates FOR SELECT TO anon USING (true); -- To allow login by username
DROP POLICY IF EXISTS "Affiliates can update their own data" ON public.affiliates;
CREATE POLICY "Affiliates can update their own data" ON public.affiliates FOR UPDATE USING (auth.uid() = user_id);

-- 5. TRIGGERS
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_affiliate_user();
