/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./*.{js,ts,jsx,tsx}",
        "./src/**/*.{js,ts,jsx,tsx}",
        "./pages/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
        "./lib/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "surface-container-low": "#1c1b1b",
                "surface-tint": "#ffb3ae",
                "on-tertiary-fixed": "#201b0c",
                "on-secondary-fixed": "#261818",
                "on-primary-fixed": "#410004",
                "error-container": "#93000a",
                "secondary-fixed-dim": "#dbc0c0",
                "on-error-container": "#ffdad6",
                "inverse-surface": "#e5e2e1",
                "tertiary": "#d0c5af",
                "surface-bright": "#3a3939",
                "background": "#131313",
                "on-tertiary": "#363020",
                "surface-container-lowest": "#0e0e0e",
                "on-surface-variant": "#e2bebc",
                "on-secondary": "#3d2c2c",
                "surface-container": "#201f1f",
                "on-secondary-container": "#c9afaf",
                "primary-container": "#a61d24",
                "tertiary-container": "#5c5543",
                "surface-variant": "#353534",
                "on-error": "#690005",
                "secondary-fixed": "#f8dcdb",
                "on-primary": "#68000c",
                "tertiary-fixed-dim": "#d0c5af",
                "outline-variant": "#5a413f",
                "on-primary-fixed-variant": "#910817",
                "on-background": "#e5e2e1",
                "outline": "#a98987",
                "on-surface": "#e5e2e1",
                "inverse-primary": "#b3272c",
                "surface": "#131313",
                "secondary": "#dbc0c0",
                "surface-dim": "#131313",
                "primary-fixed-dim": "#ffb3ae",
                "on-tertiary-container": "#d5cab3",
                "tertiary-fixed": "#ede1ca",
                "on-secondary-fixed-variant": "#554242",
                "primary": "#ffb3ae",
                "on-primary-container": "#ffb9b4",
                "surface-container-highest": "#353534",
                "inverse-on-surface": "#313030",
                "error": "#ffb4ab",
                "secondary-container": "#554242",
                "primary-fixed": "#ffdad7",
                "on-tertiary-fixed-variant": "#4d4635",
                "surface-container-high": "#2a2a2a"
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "9999px"
            },
            spacing: {
                "margin-desktop": "80px",
                "gutter": "24px",
                "section-gap": "120px",
                "unit": "8px",
                "margin-mobile": "20px"
            },
            fontFamily: {
                "label-lg": ["Montserrat", "sans-serif"],
                "body-md": ["Montserrat", "sans-serif"],
                "headline-lg-mobile": ["Playfair Display", "serif"],
                "headline-md": ["Playfair Display", "serif"],
                "display-lg": ["Playfair Display", "serif"],
                "headline-lg": ["Playfair Display", "serif"],
                "body-lg": ["Montserrat", "sans-serif"],
                "label-md": ["Montserrat", "sans-serif"]
            },
            fontSize: {
                "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.1em", fontWeight: "600" }],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
                "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
                "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "700" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }]
            }
        },
    },
    plugins: [],
}
